services:
  esc_app:
    container_name: esc_app
    image:  ghcr.io/broemp/esc:latest
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: esc_db
      DB_PORT: 5432
    env_file: .env
    ports:
      - 5173