services:
  esc_app:
    container_name: esc_app
    image: ghcr.io/broemp/esc:latest
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: esc_db
      DB_PORT: 5432
    env_file: .env
    ports:
      - 5173
    depends_on:
      - esc_db

  esc_db:
    container_name: esc_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: esc
      POSTGRES_PASSWORD: esc
      POSTGRES_DB: esc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
