extend:
  - name: pg_stat_statements
    query: |
      SELECT
        datname,
        query,
        calls,
        total_time,
        mean_time,
        rows
      FROM pg_stat_statements
      JOIN pg_database ON pg_stat_statements.dbid = pg_database.oid
    metrics:
      - datname:
          usage: "LABEL"
          description: "Name of the database"
      - query:
          usage: "LABEL"
          description: "Query text"
      - calls:
          usage: "GAUGE"
          description: "Number of times executed"
      - total_time:
          usage: "GAUGE"
          description: "Total time spent in the statement, in milliseconds"
      - mean_time:
          usage: "GAUGE"
          description: "Mean time spent in the statement, in milliseconds"
      - rows:
          usage: "GAUGE"
          description: "Total number of rows retrieved or affected by the statement"

  - name: pg_stat_activity
    query: |
      SELECT
        datname,
        state,
        count(*) as count,
        max(EXTRACT(EPOCH FROM (now() - query_start))) as max_duration
      FROM pg_stat_activity
      GROUP BY datname, state
    metrics:
      - datname:
          usage: "LABEL"
          description: "Name of the database"
      - state:
          usage: "LABEL"
          description: "Current state of the connection"
      - count:
          usage: "GAUGE"
          description: "Number of connections in this state"
      - max_duration:
          usage: "GAUGE"
          description: "Maximum duration of queries in this state, in seconds" 